### ISSUE TITLE
[FEAT] iOS 3차 과제

### ISSUE THREAD

**Issue by dev-madilyn** [29th-WE-SOPT-iOS-Part/JungJungbin#15]
## 📌  Feature Issue

* Youtube 홈 화면 구성하기
## 📝  To-do

- [x] View 나누기(상단 영역, Shorts 영역, 태그 영역, Video 영역)
- [x] 상단 영역 UI 구성 및 오토레이아웃
- [x] Shorts 영역 UI 구성 및 오토레이아웃 (CollectionView 활용)
- [x] 태그 영역 UI 구성 및 오토레이아웃
- [x] Video 영역 UI 구성 및 오토레이아웃 (TableView, Xib 활용)
- [x] 각 셀에 들어갈 더미 데이터 작성 및 적용
- [ ] 제출 전 initial storyboard Main으로 변경
