### ISSUE TITLE
[REFACTOR] iOS 3차 과제 리팩토링

### ISSUE THREAD

**Issue by dev-madilyn** [29th-WE-SOPT-iOS-Part/JungJungbin#19]
## 📌  Feature Issue

* 코드 리뷰 반영하여 리팩토링

## 📝  To-do

- [x] 사용하지 않는 import 제거
- [x] if-eles문을 swicth-case 문으로 변경
- [x] UIColor 날코딩 제거,,
- [x] setUpUI 등 함수화
