### ISSUE TITLE
[FEAT] iOS 4차 과제

### ISSUE THREAD

**Issue by dev-madilyn** [29th-WE-SOPT-iOS-Part/JungJungbin#21]
## 📌  Feature Issue

* iOS 4차 과제 : Networking

## 📝  To-do

- [x] 폴더 정리
- [x] 모든 VC에 Identifier Constant 추가
- [x] 프로필 버튼 -> 로그인 화면으로 이동
- [x] SignIn, SignUp, Welcome 다시 연결 
- [x] Setting Networking resource
- [x] 로그인 API 연결
- [x] 회원가입 API 연결
- [ ] 로그인 / 회원가입 필드 검사, 예외 처리
- [x] 로그인 / 회원가입 status code 처리
- [ ] Activity Indicator
- [ ] UserDefaults에 name 저장 후 보여 주기
