### ISSUE TITLE
[REFACTOR] iOS 1차 과제 리팩토링

### ISSUE THREAD

**Issue by dev-madilyn** [29th-WE-SOPT-iOS-Part/JungJungbin#8]
## 📌  Feature Issue

1차 과제 리팩토링에 도움을 주신 승찬 님(aka 금잔디파)께 감사합니다...

## 📝  To-do

- [ ] viewDidLoad 안의 UI 그리는 작업들 함수화
- [ ] UIColor extension해서 바로 쓸 수 있게!
- [ ] 텍스트필드 검사하는 기능 함수화
- [ ] 간단한 if-else문 삼항연산자 사용
